const AGENTS = [
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    vendor: "Microsoft / GitHub",
    logo: "https://github.githubassets.com/images/modules/site/copilot/copilot.png",
    logoFallback: "GC",
    logoColor: "#1a1a2e",
    description: "嵌入 IDE 的 AI 编程助手，提供代码补全、聊天和代码审查功能。",
    website: "https://github.com/features/copilot",
    category: ["代码补全", "聊天", "IDE插件"],
    pricing: {
      free: true,
      freeDetail: "学生/开源免费",
      paid: "$10/月 个人版",
      enterprise: "$19/月/用户 企业版",
    },
    features: {
      codeCompletion: true,
      chat: true,
      codeReview: true,
      debugging: true,
      testing: true,
      multiFile: true,
      webSearch: false,
      agentMode: true,
      terminalIntegration: true,
      imageInput: false,
    },
    ides: ["VS Code", "JetBrains", "Visual Studio", "Neovim", "Vim"],
    languages: "全部主流语言",
    contextWindow: "128K tokens",
    model: "GPT-4o / Claude 3.5 Sonnet",
    pros: ["深度集成 GitHub 生态", "企业级安全合规", "多 IDE 支持", "Agent 模式强大"],
    cons: ["免费版功能受限", "依赖网络连接"],
    rating: 4.7,
    popular: true,
    tags: ["主流", "企业"],
  },
  {
    id: "cursor",
    name: "Cursor",
    vendor: "Anysphere",
    logo: "",
    logoFallback: "Cur",
    logoColor: "#6c5ce7",
    description: "专为 AI 编程打造的 IDE，支持多文件编辑、Composer 和 Agent 模式。",
    website: "https://cursor.com",
    category: ["AI IDE", "代码补全", "聊天"],
    pricing: {
      free: true,
      freeDetail: "免费版含 2000 次补全",
      paid: "$20/月 Pro",
      enterprise: "$40/月/用户 Business",
    },
    features: {
      codeCompletion: true,
      chat: true,
      codeReview: false,
      debugging: true,
      testing: true,
      multiFile: true,
      webSearch: true,
      agentMode: true,
      terminalIntegration: true,
      imageInput: true,
    },
    ides: ["Cursor (独立IDE, 基于VS Code)"],
    languages: "全部主流语言",
    contextWindow: "200K tokens",
    model: "Claude 3.5 Sonnet / GPT-4o / Gemini",
    pros: ["Composer 多文件编辑体验优秀", "Agent 自动执行任务", "支持多种前沿模型", "图片输入理解"],
    cons: ["需要切换到新 IDE", "Pro 版价格较高"],
    rating: 4.8,
    popular: true,
    tags: ["主流", "AI原生"],
  },
  {
    id: "windsurf",
    name: "Windsurf",
    vendor: "Codeium",
    logo: "",
    logoFallback: "WS",
    logoColor: "#00b894",
    description: "Codeium 推出的 AI IDE，Cascade Agent 支持深度上下文感知的多步任务执行。",
    website: "https://windsurf.com",
    category: ["AI IDE", "代码补全", "聊天"],
    pricing: {
      free: true,
      freeDetail: "免费版含基础功能",
      paid: "$15/月 Pro",
      enterprise: "联系销售",
    },
    features: {
      codeCompletion: true,
      chat: true,
      codeReview: false,
      debugging: true,
      testing: true,
      multiFile: true,
      webSearch: true,
      agentMode: true,
      terminalIntegration: true,
      imageInput: false,
    },
    ides: ["Windsurf (独立IDE, 基于VS Code)"],
    languages: "全部主流语言",
    contextWindow: "128K tokens",
    model: "Claude 3.5 Sonnet / GPT-4o",
    pros: ["Cascade Agent 任务执行能力强", "免费版功能丰富", "价格相对实惠"],
    cons: ["生态相对较新", "插件兼容性待提升"],
    rating: 4.5,
    popular: true,
    tags: ["主流", "AI原生"],
  },
  {
    id: "claude",
    name: "Claude",
    vendor: "Anthropic",
    logo: "",
    logoFallback: "Cl",
    logoColor: "#cc5500",
    description: "Anthropic 的 AI 助手，擅长长文本理解和代码生成，提供 claude.ai 和 API。",
    website: "https://claude.ai",
    category: ["聊天", "代码生成", "API"],
    pricing: {
      free: true,
      freeDetail: "每日限量免费",
      paid: "$20/月 Pro",
      enterprise: "$30/月/用户 Team",
    },
    features: {
      codeCompletion: false,
      chat: true,
      codeReview: true,
      debugging: true,
      testing: true,
      multiFile: true,
      webSearch: false,
      agentMode: true,
      terminalIntegration: false,
      imageInput: true,
    },
    ides: ["VS Code (通过插件)", "JetBrains (通过插件)"],
    languages: "全部主流语言",
    contextWindow: "200K tokens",
    model: "Claude 3.5 Sonnet / Claude 3 Opus",
    pros: ["200K 超长上下文", "代码理解能力强", "安全对齐好", "支持 Artifacts 在线预览"],
    cons: ["无实时补全", "网页端操作为主", "联网搜索能力有限"],
    rating: 4.6,
    popular: true,
    tags: ["主流", "长上下文"],
  },
  {
    id: "codeium",
    name: "Codeium",
    vendor: "Codeium",
    logo: "",
    logoFallback: "Cdm",
    logoColor: "#09c484",
    description: "永久免费的 AI 代码补全工具，支持 70+ 语言和多款 IDE，适合个人开发者。",
    website: "https://codeium.com",
    category: ["代码补全", "聊天", "IDE插件"],
    pricing: {
      free: true,
      freeDetail: "个人永久免费",
      paid: "$12/月 Teams",
      enterprise: "联系销售",
    },
    features: {
      codeCompletion: true,
      chat: true,
      codeReview: false,
      debugging: false,
      testing: false,
      multiFile: false,
      webSearch: false,
      agentMode: false,
      terminalIntegration: false,
      imageInput: false,
    },
    ides: ["VS Code", "JetBrains", "Vim/Neovim", "Emacs", "40+"],
    languages: "70+ 语言",
    contextWindow: "—",
    model: "Codeium 自研模型",
    pros: ["个人永久免费", "IDE 覆盖最广", "响应速度快", "自托管方案"],
    cons: ["功能相对基础", "Agent 能力弱", "无多文件编辑"],
    rating: 4.2,
    popular: false,
    tags: ["免费", "轻量"],
  },
  {
    id: "tabnine",
    name: "Tabnine",
    vendor: "Tabnine",
    logo: "",
    logoFallback: "Tab",
    logoColor: "#5352ed",
    description: "注重隐私保护的 AI 代码补全工具，支持本地模型和企业私有化部署。",
    website: "https://tabnine.com",
    category: ["代码补全", "IDE插件"],
    pricing: {
      free: true,
      freeDetail: "基础功能免费",
      paid: "$12/月 Pro",
      enterprise: "$39/月/用户",
    },
    features: {
      codeCompletion: true,
      chat: true,
      codeReview: false,
      debugging: false,
      testing: false,
      multiFile: false,
      webSearch: false,
      agentMode: false,
      terminalIntegration: false,
      imageInput: false,
    },
    ides: ["VS Code", "JetBrains", "Eclipse", "Visual Studio"],
    languages: "全部主流语言",
    contextWindow: "—",
    model: "Tabnine 自研 + GPT 混合",
    pros: ["私有化部署选项", "隐私保护强", "代码不离开本地可选", "合规认证多"],
    cons: ["补全质量低于 Copilot", "Agent 功能缺失", "界面较旧"],
    rating: 3.9,
    popular: false,
    tags: ["隐私", "企业"],
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    vendor: "OpenAI",
    logo: "",
    logoFallback: "GPT",
    logoColor: "#10a37f",
    description: "OpenAI 的通用 AI 助手，支持代码生成、调试、解释，提供网页和 API 两种方式。",
    website: "https://chat.openai.com",
    category: ["聊天", "代码生成", "API"],
    pricing: {
      free: true,
      freeDetail: "限量免费使用",
      paid: "$20/月 Plus",
      enterprise: "$30/月/用户 Team",
    },
    features: {
      codeCompletion: false,
      chat: true,
      codeReview: true,
      debugging: true,
      testing: true,
      multiFile: false,
      webSearch: true,
      agentMode: true,
      terminalIntegration: false,
      imageInput: true,
    },
    ides: ["VS Code (通过插件)"],
    languages: "全部主流语言",
    contextWindow: "128K tokens",
    model: "GPT-4o / GPT-o1",
    pros: ["知名度最高", "联网搜索", "图片理解", "插件生态丰富"],
    cons: ["无实时代码补全", "需要手动粘贴代码", "IDE 集成弱"],
    rating: 4.5,
    popular: true,
    tags: ["主流", "通用"],
  },
  {
    id: "gemini-code",
    name: "Gemini Code Assist",
    vendor: "Google",
    logo: "",
    logoFallback: "GCA",
    logoColor: "#4285f4",
    description: "Google 的 AI 编程助手，基于 Gemini 模型，深度集成 Google Cloud 和 Android Studio。",
    website: "https://cloud.google.com/gemini/docs/codeassist/overview",
    category: ["代码补全", "聊天", "IDE插件"],
    pricing: {
      free: true,
      freeDetail: "个人版免费",
      paid: "$19/月 Standard",
      enterprise: "$45/月/用户 Enterprise",
    },
    features: {
      codeCompletion: true,
      chat: true,
      codeReview: true,
      debugging: true,
      testing: true,
      multiFile: true,
      webSearch: false,
      agentMode: true,
      terminalIntegration: true,
      imageInput: false,
    },
    ides: ["VS Code", "JetBrains", "Cloud Shell Editor", "Android Studio"],
    languages: "全部主流语言",
    contextWindow: "1M tokens",
    model: "Gemini 1.5 Pro / 2.0 Flash",
    pros: ["100 万超长上下文", "深度集成 GCP", "Android 开发最优", "企业级安全"],
    cons: ["中文支持较弱", "非 Google 生态用户体验一般"],
    rating: 4.3,
    popular: false,
    tags: ["Google生态", "长上下文"],
  },
  {
    id: "amazon-q",
    name: "Amazon Q Developer",
    vendor: "Amazon",
    logo: "",
    logoFallback: "AQ",
    logoColor: "#ff9900",
    description: "Amazon 的 AI 编程助手，深度集成 AWS，支持代码转换、安全扫描和测试生成。",
    website: "https://aws.amazon.com/q/developer/",
    category: ["代码补全", "聊天", "IDE插件"],
    pricing: {
      free: true,
      freeDetail: "个人版免费",
      paid: "$19/月/用户 Pro",
      enterprise: "联系销售",
    },
    features: {
      codeCompletion: true,
      chat: true,
      codeReview: true,
      debugging: true,
      testing: true,
      multiFile: true,
      webSearch: false,
      agentMode: true,
      terminalIntegration: true,
      imageInput: false,
    },
    ides: ["VS Code", "JetBrains", "AWS Cloud9"],
    languages: "15+ 语言",
    contextWindow: "128K tokens",
    model: "Amazon 自研模型",
    pros: ["深度集成 AWS", "安全漏洞扫描", "代码迁移转换", "合规认证完善"],
    cons: ["非 AWS 用户价值有限", "补全质量中等"],
    rating: 4.0,
    popular: false,
    tags: ["AWS生态", "企业"],
  },
  {
    id: "continue",
    name: "Continue",
    vendor: "Continue.dev",
    logo: "",
    logoFallback: "Con",
    logoColor: "#845ef7",
    description: "开源 AI 编程助手，可自由接入任意模型（本地或云端），高度可定制。",
    website: "https://continue.dev",
    category: ["代码补全", "聊天", "IDE插件", "开源"],
    pricing: {
      free: true,
      freeDetail: "完全免费开源",
      paid: "—",
      enterprise: "联系商业支持",
    },
    features: {
      codeCompletion: true,
      chat: true,
      codeReview: false,
      debugging: true,
      testing: false,
      multiFile: true,
      webSearch: false,
      agentMode: true,
      terminalIntegration: true,
      imageInput: false,
    },
    ides: ["VS Code", "JetBrains"],
    languages: "全部主流语言",
    contextWindow: "取决于所接入模型",
    model: "自由选择：Ollama/Claude/GPT/Gemini等",
    pros: ["完全开源免费", "支持本地 Ollama 模型", "高度可定制", "数据不外泄"],
    cons: ["需要自行配置模型", "功能需要自己组装", "新手门槛较高"],
    rating: 4.4,
    popular: false,
    tags: ["开源", "隐私", "可定制"],
  },
];

const FEATURE_LABELS = {
  codeCompletion: "实时代码补全",
  chat: "AI 对话",
  codeReview: "代码审查",
  debugging: "调试辅助",
  testing: "测试生成",
  multiFile: "多文件编辑",
  webSearch: "联网搜索",
  agentMode: "Agent 模式",
  terminalIntegration: "终端集成",
  imageInput: "图片输入",
};

const CATEGORIES = [
  "全部",
  "代码补全",
  "聊天",
  "AI IDE",
  "IDE插件",
  "开源",
  "API",
];
